#FOURSIGHT_PREFIX = 'foursight-cgap'
FOURSIGHT_PREFIX = 'cgap-biotest-main-foursight'
DEV_ENV = 'cgap'
#HOST = 'https://search-foursight-fourfront-ylxn33a5qytswm63z52uytgkm4.us-east-1.es.amazonaws.com'
HOST = 'https://vpc-es-cgap-wolf-nzizh2u7cygiokkxxnar4te2tu.us-east-1.es.amazonaws.com:443'